version: 1.0.{build}

image: Visual Studio 2019

before_build:
    - dotnet restore ".\src\FligthtManager.sln"

build_script:
    - dotnet build ".\src\FligthtManager.sln"

test_script:
    - dotnet test ".\src\FligthtManager.sln"